# Проверка preprocessing

Этот notebook проверяет подготовку данных после загрузки Excel-файла.

In [2]:
from importlib import import_module
from pathlib import Path
import sys

# Определяем корень проекта, даже если notebook запущен из папки tests_ipynb.
project_root = Path.cwd()
if not (project_root / "data" / "trade.xlsx").exists():
    project_root = project_root.parent

# Добавляем корень проекта в пути импорта.
sys.path.insert(0, str(project_root))

loader = import_module("src.1_data_loader.loader")
preprocessing = import_module("src.2_preprocessing.preprocessing")

In [3]:
# Загружаем данные и выполняем preprocessing.
raw_data = loader.load_excel_data(project_root / "data" / "trade.xlsx")
prepared_data = preprocessing.preprocess_trade_data(raw_data)

prepared_data.head()

  Import_Export  Year  Month   TNVED  Country  US_dollars
0        Export  2022      1  841810  Армения   117946.29
1        Export  2022      1  847141  Армения      467.32
2        Export  2022      1  841830  Армения      204.32
3        Export  2022      1  841840  Армения     7252.98
4        Export  2022      1  841850  Армения   103480.86

In [4]:
# Проверяем результат базовой подготовки.
assert prepared_data["Month"].between(1, 12).all()
assert set(prepared_data["Import_Export"].unique()) == {"Import", "Export"}
assert prepared_data["US_dollars"].gt(0).all()
assert "0" not in set(prepared_data["TNVED"])

prepared_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 139216 entries, 0 to 139215
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Import_Export  139216 non-null  str
 1   Year           139216 non-null  int64
 2   Month          139216 non-null  int64
 3   TNVED          139216 non-null  str
 4   Country        139216 non-null  str
 5   US_dollars     139216 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 6.4 MB

In [5]:
# Формируем таблицы для будущего расчета критериев.
yearly_trade = preprocessing.make_yearly_trade_table(prepared_data)
country_import = preprocessing.make_country_import_table(prepared_data)

display(yearly_trade.head(30))
display(country_import.head(30))

     TNVED  Year        Import       Export
0   841810  2022  1.218701e+08  55165403.63
1   841810  2023  2.335620e+08  39160441.71
2   841810  2024  2.419143e+08  24915442.10
3   841810  2025  2.084822e+08  18947441.75
4   841821  2022  3.018812e+07   3557820.77
5   841821  2023  3.893443e+07   2419886.99
6   841821  2024  4.255427e+07    655616.60
7   841821  2025  4.494547e+07    296556.92
8   841829  2022  3.088085e+06    201534.81
9   841829  2023  3.217544e+06   1297322.01
10  841829  2024  4.943324e+06    806031.45
11  841829  2025  4.078745e+06    968981.47
12  841830  2022  2.989839e+07  10293938.84
13  841830  2023  4.119857e+07   7475886.38
14  841830  2024  3.930760e+07   4161486.95
15  841830  2025  3.347578e+07   2247578.73
16  841840  2022  1.607860e+07   3311343.35
17  841840  2023  2.122139e+07   2314804.10
18  841840  2024  2.203188e+07   1534260.68
19  841840  2025  1.886445e+07   1048776.96
20  841850  2022  1.486245e+07  88594026.87
21  841850  2023  1.329434e+07  32439223.50
22  841850  2024  2.920080e+07  10973714.49
23  841850  2025  3.413444e+07   6095472.72
24  841861  2022  4.699087e+06     16145.55
25  841861  2023  1.094029e+07     25378.98
26  841861  2024  3.930887e+06      4869.78
27  841861  2025  4.227753e+06     43858.43
28  841869  2022  6.861618e+07  12200911.80
29  841869  2023  1.237447e+08  12632055.23

     TNVED  Year      Country  Import_by_country
0   841810  2022  Азербайджан       5.000000e+02
1   841810  2022      Армения       1.495228e+05
2   841810  2022     Германия       8.224363e+06
3   841810  2022       Грузия       6.202560e+04
4   841810  2022       Египет       7.735000e+04
5   841810  2022       Италия       2.168051e+06
6   841810  2022    Казахстан       2.380599e+06
7   841810  2022        Китай       5.983865e+07
8   841810  2022       Латвия       1.386915e+05
9   841810  2022        Литва       8.368200e+05
10  841810  2022       Польша       9.688027e+06
11  841810  2022      Румыния       4.873263e+06
12  841810  2022       Сербия       2.856065e+07
13  841810  2022       Турция       3.976073e+06
14  841810  2022    Финляндия       8.722700e+02
15  841810  2022    Швейцария       1.089324e+04
16  841810  2022      Эстония       5.164532e+04
17  841810  2022  Южная Корея       7.906930e+05
18  841810  2022       Япония       4.138408e+04
19  841810  2023  Азербайджан       1.294118e+04
20  841810  2023      Армения       4.888506e+06
21  841810  2023     Германия       5.444245e+06
22  841810  2023       Египет       1.227614e+05
23  841810  2023        Индия       1.045589e+04
24  841810  2023       Италия       3.640971e+05
25  841810  2023    Казахстан       4.052408e+06
26  841810  2023     Киргизия       7.162000e+03
27  841810  2023        Китай       1.411911e+08
28  841810  2023       Латвия       7.211622e+04
29  841810  2023        Литва       1.527649e+06